---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: false

platforms:
  - name: ubuntu-12.04-chef-11
    driver_config:
      box: ubuntu-12.04.5-chef-11.18.6
      box_url: http://d30mo6j6uouwb9.cloudfront.net/vagrant-boxes/ubuntu-12.04.5-chef-11.18.6-virtualbox.box
suites:
  - name: purrbiscuit
    driver:
      network:
      - [ "private_network", { ip: "192.168.50.4" } ]
    run_list:
      - recipe[purrbiscuit]
    attributes:
